version: "3.8" # Specify Docker Compose version

services:
  bookings-app:
    build: . # Build the image from the current directory (where Dockerfile is located)
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
      # - GO111MODULE=on  # Enable Go modules
      - PORT=8080 # Set the port for the Go application
      - DATABASE_URL=postgres://root:bookings@postgres:5432/bookings # Example database configuration (if applicable)
    depends_on:
      - postgres # Dependency on a database service (if applicable)

  postgres: # Example database service (if needed)
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: bookings
      POSTGRES_DB: bookings
